---
- name: Check if Leader Host is Defined
  fail:
    msg: "k3s_leader_host variable must be defined in group_vars"
  when: k3s_leader_host is not defined

- name: Check current K3s version
  command: k3s --version
  register: k3s_current_version
  changed_when: false
  failed_when: false

- name: Fetch K3s Token from Leader
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  delegate_to: "{{ k3s_leader_host }}"
  register: k3s_token_slurp
  become: true

- name: Install/Upgrade K3s Agent
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_install_version }} sh -s - agent \
    --server https://{{ hostvars[k3s_leader_host]['ansible_host'] }}:6443 \
    --token {{ k3s_token_slurp.content | b64decode | trim }} \
    --node-external-ip {{ ansible_host }} \
    --kubelet-arg="fail-swap-on=false"
  when: >
    k3s_current_version.rc != 0 or
    k3s_install_version not in k3s_current_version.stdout

- name: Label Worker Node with Role
  command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=true --overwrite
  delegate_to: "{{ k3s_leader_host }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: worker_label_result
  changed_when: "'not labeled' not in worker_label_result.stdout"

- name: Label Worker Node with Zone (City)
  command: kubectl label node {{ inventory_hostname }} topology.kubernetes.io/zone={{ inventory_hostname[:3] }} --overwrite
  delegate_to: "{{ k3s_leader_host }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: zone_label_result
  changed_when: "'not labeled' not in zone_label_result.stdout"

- name: Label Worker Node with Region
  command: kubectl label node {{ inventory_hostname }} topology.kubernetes.io/region={{ node_region | default('us-west') }} --overwrite
  delegate_to: "{{ k3s_leader_host }}"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  register: region_label_result
  changed_when: "'not labeled' not in region_label_result.stdout"
