---
traefik_sites:
  - domain: "xxx.xxx.com"
    upstream: "http://127.0.0.1:8080"

xray_host_clients:
  - id: "xxxx"
    email: "temp-xxx"

tailscale_derp_enabled: false
tailscale_derp_hostname: ""
tailscale_enable_peer_relay: false
tailscale_derp_http_port: xxxx