---
monitoring_enable_node_exporter: false
node_exporter_version: "1.10.2"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_port: 9100
node_exporter_archive: "node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_archive }}"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_checksum: "sha256:c46e5b6f53948477ff3a19d97c58307394a29fe64a01905646f026ddc32cb65b"
