---
- name: Create Xray directory
  file:
    path: /usr/local/etc/xray
    state: directory
    mode: '0755'

- name: Install Xray
  shell: |
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
  args:
    creates: /usr/local/bin/xray

- name: Configure Xray
  template:
    src: xray_config.json.j2
    dest: /usr/local/etc/xray/config.json
    mode: '0644'
  notify: Restart Xray

- name: Install Xray Exporter
  shell: |
    curl -L -o /usr/local/bin/xray-exporter https://github.com/teddysun/xray-exporter/releases/download/v1.0.0/xray-exporter_linux_amd64
    chmod +x /usr/local/bin/xray-exporter
  args:
    creates: /usr/local/bin/xray-exporter

- name: Configure Xray Exporter Service
  template:
    src: xray-exporter.service.j2
    dest: /etc/systemd/system/xray-exporter.service
    mode: '0644'
  notify: Restart Xray Exporter

- name: Ensure Xray Exporter is running
  service:
    name: xray-exporter
    state: started
    enabled: true

- name: Ensure Xray is running
  service:
    name: xray
    state: started
    enabled: true

- name: Force immediate handler execution
  meta: flush_handlers
