---
- name: Create Xray directory
  file:
    path: /usr/local/etc/xray
    state: directory
    mode: '0755'

- name: Install Xray
  shell: |
    bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
  args:
    creates: /usr/local/bin/xray

- name: Configure Xray
  template:
    src: xray_config.json.j2
    dest: /usr/local/etc/xray/config.json
    mode: '0644'
  notify: Restart Xray

- name: Install Xray Exporter - Download to tmp
  ansible.builtin.get_url:
    url: "{{ xray_exporter_download_url }}"
    dest: "/tmp/{{ xray_exporter_binary }}"
    mode: '0644'
  register: download_xray_exporter

- name: Install Xray Exporter - Copy to install dir
  ansible.builtin.copy:
    src: "/tmp/{{ xray_exporter_binary }}"
    dest: "{{ xray_exporter_install_dir }}/xray-exporter"
    mode: '0755'
    owner: nobody
    group: nogroup
    remote_src: true
  notify: Restart Xray Exporter

- name: Configure Xray Exporter Service
  template:
    src: xray-exporter.service.j2
    dest: /etc/systemd/system/xray-exporter.service
    mode: '0644'
  notify: Restart Xray Exporter

- name: Ensure Xray Exporter is running
  service:
    name: xray-exporter
    state: started
    enabled: true

- name: Ensure Xray is running
  service:
    name: xray
    state: started
    enabled: true

- name: Force immediate handler execution
  meta: flush_handlers
