---
- name: Allow standard Kubernetes TCP ports
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  loop: "{{ firewall_allowed_tcp_ports }}"
  when: firewall_enable_cluster_trust | bool
  notify: Save Firewall Rules

- name: Allow standard Kubernetes UDP ports
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: udp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  loop: "{{ firewall_allowed_udp_ports }}"
  when: firewall_enable_cluster_trust | bool
  notify: Save Firewall Rules

- name: Allow NodePorts (TCP)
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: tcp
    destination_port: 30000:32767
    jump: ACCEPT
    action: append
    ip_version: ipv4
  when: firewall_enable_nodeports | bool
  notify: Save Firewall Rules

- name: Allow NodePorts (UDP)
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: udp
    destination_port: 30000:32767
    jump: ACCEPT
    action: append
    ip_version: ipv4
  when: firewall_enable_nodeports | bool
  notify: Save Firewall Rules

- name: Allow Node Exporter (TCP 9100) from cluster nodes
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: tcp
    destination_port: 9100
    source: "{{ hostvars[item].ansible_host }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  loop: "{{ groups['cluster'] }}"
  when: 
    - firewall_enable_cluster_trust | bool
    - hostvars[item].ansible_host is defined
  notify: Save Firewall Rules

- name: Allow Xray Exporter (TCP 9550) from cluster nodes
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: tcp
    destination_port: "{{ xray_exporter_port }}"
    source: "{{ hostvars[item].ansible_host }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  loop: "{{ groups['cluster'] }}"
  when: 
    - firewall_enable_cluster_trust | bool
    - hostvars[item].ansible_host is defined
  notify: Save Firewall Rules
