---
- name: Install iptables-persistent
  apt:
    name:
      - iptables-persistent
      - netfilter-persistent
    state: present

# 1. Setup Chains & Policies
- import_tasks: setup.yml

# 2. Base Rules (SSH, ICMP, Loopback)
- import_tasks: base.yml

# 3. Cluster Rules (K8s, Cilium, NodePorts)
- include_tasks: cluster.yml

# 4. App Rules
- import_tasks: ingress.yml

# 5. Tailscale Rules
- import_tasks: tailscale.yml

# 6. DERP Rules
- import_tasks: derp.yml

# 7. Final Drop Rule
- name: Log and Drop at end of ANSIBLE-FW
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    jump: DROP
    action: append
    ip_version: ipv4
  notify: Save Firewall Rules

- name: Log and Drop at end of ANSIBLE-FW6
  ansible.builtin.iptables:
    chain: ANSIBLE-FW6
    jump: DROP
    action: append
    ip_version: ipv6
  notify: Save IPv6 Firewall Rules

# 8. Save rules to disk immediately
- meta: flush_handlers

- name: Enable netfilter-persistent
  service:
    name: netfilter-persistent
    state: started
    enabled: true
