---
- name: Allow Tailscale Trust Zone
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    in_interface: tailscale0
    jump: ACCEPT
    action: append
    ip_version: ipv4
  when: firewall_enable_tailscale_trust | bool
  notify: Save Firewall Rules

- name: Allow Tailscale Peer Relay
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: udp
    destination_port: "{{ tailscale_peer_relay_port }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  when: tailscale_enable_peer_relay | default(false) | bool
  notify: Save Firewall Rules

- name: Allow Tailscale DERP STUN
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: udp
    destination_port: "{{ tailscale_derp_stun_port }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  when: tailscale_derp_enabled | default(false) | bool
  notify: Save Firewall Rules
