---
- name: Allow Xray Service
  ansible.builtin.iptables:
    chain: ANSIBLE-FW
    protocol: tcp
    destination_port: "{{ xray_port_tcp }}"
    jump: ACCEPT
    action: append
    ip_version: ipv4
  when: firewall_enable_xray | bool
  notify: Save Firewall Rules

- name: Allow Xray Service (IPv6)
  ansible.builtin.iptables:
    chain: ANSIBLE-FW6
    protocol: tcp
    destination_port: "{{ xray_port_tcp }}"
    jump: ACCEPT
    action: append
    ip_version: ipv6
  when: firewall_enable_xray | bool
  notify: Save IPv6 Firewall Rules
