---
- block:
    - name: Create node_exporter group
      group:
        name: "{{ node_exporter_group }}"
        state: present
        system: true

    - name: Create node_exporter user
      user:
        name: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        shell: /usr/sbin/nologin
        system: true
        create_home: false

    - name: Download node_exporter
      get_url:
        url: "{{ node_exporter_download_url }}"
        dest: "/tmp/{{ node_exporter_archive }}"
        mode: '0644'
        checksum: "sha256:c46e5b6f53948477ff3a19d97c58307394a29fe64a01905646f026ddc32cb65b"
      register: download_node_exporter

    - name: Unarchive node_exporter
      unarchive:
        src: "/tmp/{{ node_exporter_archive }}"
        dest: "/tmp"
        remote_src: true
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

    - name: Install node_exporter binary
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_install_dir }}/node_exporter"
        mode: '0755'
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        remote_src: true
      notify: Restart node_exporter

    - name: Create systemd service unit
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'
      notify: Restart node_exporter

    - name: Enable and start node_exporter
      service:
        name: node_exporter
        state: started
        enabled: true
      when: monitoring_enable_node_exporter | default(false) | bool
