---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\b'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname.split('.')[0] }}"
    owner: root
    group: root
    mode: '0644'
