---
tailscale_auth_key: ""
tailscale_advertise_exit_node: true

# --- Firewall Capabilities ---
firewall_enable_tailscale_trust: true
firewall_enable_cluster_trust: false
firewall_enable_nodeports: false
firewall_enable_ingress: true
# Monitoring
monitoring_enable_node_exporter: true

# Xray Relay Configuration
xray_relay_rules:
  - listen: 10001
    target_addr: "1.2.3.4"
    target_port: 10000
